### ISSUE TITLE
framework cannot be loaded

### ISSUE THREAD

**Issue by njkirkpatrick** [alberti42/Keynote-Progress-Bar#1] opened 2024-09-17 16:53 UTC
When trying to compile the AppleScript, I get the error "The bundle "KeynoteProgressBarHelper" couldn't be loaded". Also, should the framework path be /Library/Frameworks? I don't have a Frameworks directory in /Users/username/Library

**Comment by alberti42** [comment] 2024-09-17 17:32
Yes, you need to create a folder in ~/Library/Frameworks. Apple does not create by default.

**Comment by njkirkpatrick** [comment] 2024-09-17 18:02
Still can't get past the error:

>  error "The bundle “KeynoteProgressBarHelper” couldn’t be loaded." number -4960 from framework "KeynoteProgressBarHelper"

**Comment by alberti42** [comment] 2024-09-17 19:13
I would need much more information to help you. Is it the message you get when you try to save the AppleScript as a .scpt file?

Did you first compile with Xcode the Objective-C code? Did you install the framework in the folder `~/Library/Frameworks`?

**Comment by njkirkpatrick** [comment] 2024-09-17 19:18
That is the error I get when trying to compile the AppleScript to save as a .scpt. 

I compiled the Objective-C code with Xcode and signed it (not sure if that matters). Then I moved the .framework folder it created to ~/Library/Frameworks. I also tried using /Library/Frameworks instead, but the same error happens

**Comment by alberti42** [comment] 2024-09-17 20:16
Ok, I suspect the problem is with Apple policy. They deemed it dangerous to allow user to run such a code.

Check the post https://forums.developer.apple.com/forums/thread/121080

I wrote the code before 2019 but maintained till today. The thing is that in the past years I moved to [Script Debugger](https://latenightsw.com/) which is expensive but very powerful. I can reproduce your error with Apple Script Editor but as the post says, there is no problem with Script Debugger. Once you have compiled the app, you do not need Script Debugger to run it. I actually run it from [LaunchBar](https://www.obdev.at/products/launchbar/index.html).

We simply need to figure out how to overcome Apple limits. Of course I understand that Apple would like only certified programmers to share code, because this code has been strictly reviewed by Apple.

Running code from the Internet (as this one) can always hide the potential of malicious code. Only few users are skilled enough that they can review the entire code, even if the code is open source.

We need to do some research to understand how to overcome Apple barrier without paying for Script Debugger.

**Comment by njkirkpatrick** [comment] 2024-09-18 17:48
Wow thank you for doing all this! I can finally get the Add Progress Bar to Keynote.app to open, but now I get this error when I do so.
<img width="372" alt="Screenshot 2024-09-18 at 1 45 24 PM" src="https://github.com/user-attachments/assets/41895d70-6041-40dd-8af2-c33ccd92a4df">

**Comment by njkirkpatrick** [comment] 2024-09-18 18:07
Thank you for doing all this! It totally works!

**Comment by alberti42** [comment] 2024-09-18 20:23
Awesome. Can you say something more about what made it work? Was the application in the .zip file? If so, I will post it on the front page for others.

**Comment by njkirkpatrick** [comment] 2024-09-18 21:09
Yes the application in the .zip file made it work.

**Comment by alberti42** [comment] 2024-10-06 17:17
I released a new version of the application that fixes some bugs. I close this issue as I believe the problem is now fixed. The framework inside the AppleScript application does not throw an error on my computer.

I am not sure if you had to remove the quarantine flag after downloading the zip or not. If so, I would like to include a note in the instructions. Feel free to contact me directly over GitHub: @alberti42

**Closed by alberti42** 2024-10-06 17:17 UTC
